"""Request and response shapes for the visit API (PRD §5.1).

A reading is the device's Bluetooth message (see firmware/ssos_main) plus the
time the phone received it, so the app can forward it unchanged:
  {"dev":"F294","fw":"0.4.0","sensor":"TDS","value":58,"unit":"ppm",
   "status":"settled","temp":25.3, "taken_at":"2026-10-08T10:01:00+05:30"}
"""

from enum import Enum
from typing import Optional, Union
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, model_validator


class Sensor(str, Enum):
    TEMP = "TEMP"
    TDS = "TDS"
    VOLT = "VOLT"
    PRESS = "PRESS"
    SOUND = "SOUND"  # measured by the phone's microphone, not the device


class Result(str, Enum):
    pass_ = "pass"
    warn = "warn"
    fail = "fail"


class Status(str, Enum):
    settled = "settled"
    unstable = "unstable"
    fault = "fault"


# Unit and accepted range per sensor, matching what the firmware sends. Ranges
# are the PRD ranges with headroom, to catch garbage (e.g. -127 °C from a
# disconnected DS18B20), not to judge pass/fail.
SENSOR_SPEC = {
    Sensor.TEMP: ("C", -55.0, 125.0),
    Sensor.TDS: ("ppm", 0.0, 2000.0),
    Sensor.VOLT: ("V", 0.0, 300.0),
    Sensor.PRESS: ("bar", 0.0, 16.0),
    Sensor.SOUND: ("dB", 0.0, 150.0),
}

# Sensor-specific fields the firmware adds (TDS water "temp", VOLT "min"/"max"/"cal")
# are kept in the reading's `extra` column. Capped so the column can't be abused.
MAX_EXTRA_FIELDS = 8
Scalar = Union[bool, int, float, str, None]


class Reading(BaseModel):
    model_config = ConfigDict(extra="allow")

    sensor: Sensor
    value: Optional[float]  # null when status is "fault"
    unit: str
    status: Optional[Status] = None  # always sent by the device
    result: Optional[Result] = None  # pass/warn/fail, once thresholds are agreed (PRD §8)
    dev: Optional[str] = Field(default=None, min_length=1, max_length=32)
    fw: Optional[str] = Field(default=None, min_length=1, max_length=32)
    battery_v: Optional[float] = Field(default=None, ge=0, le=10)
    taken_at: AwareDatetime  # added by the phone when the message arrives

    @model_validator(mode="after")
    def check_sensor(self) -> "Reading":
        unit, low, high = SENSOR_SPEC[self.sensor]
        if self.unit != unit:
            raise ValueError(f"{self.sensor.value} must be in {unit}, got {self.unit!r}")
        if self.value is None:
            if self.status != Status.fault:
                raise ValueError("value can only be null when status is fault")
        elif not low <= self.value <= high:
            raise ValueError(f"{self.sensor.value} {self.value} {unit} is outside {low}..{high}")
        if self.sensor != Sensor.SOUND:
            if self.dev is None or self.fw is None or self.status is None:
                raise ValueError("device readings need dev, fw and status")
        extra = self.model_extra or {}
        if len(extra) > MAX_EXTRA_FIELDS:
            raise ValueError(f"at most {MAX_EXTRA_FIELDS} extra fields")
        for key, v in extra.items():
            if len(key) > 32 or not isinstance(v, (bool, int, float, str, type(None))) or (
                isinstance(v, str) and len(v) > 64
            ):
                raise ValueError(f"extra field {key!r} must be a short number, string or boolean")
        return self

    def to_row(self) -> dict:
        """The shape submit_visit() in the database expects."""
        return {
            "sensor": self.sensor.value,
            "value": self.value,
            "unit": self.unit,
            "result": self.result.value if self.result else None,
            "status": self.status.value if self.status else None,
            "battery_v": self.battery_v,
            "device_id": self.dev,
            "firmware_version": self.fw,
            "taken_at": self.taken_at.isoformat(),
            "extra": dict(self.model_extra) if self.model_extra else None,
        }


class Customer(BaseModel):
    name: str = Field(min_length=1, max_length=200)
    phone: Optional[str] = Field(default=None, max_length=32)
    address: Optional[str] = Field(default=None, max_length=500)


class Location(BaseModel):
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)
    label: Optional[str] = Field(default=None, max_length=200)


class VisitIn(BaseModel):
    id: UUID  # generated by the app, so a retried submit is not saved twice
    # Taken from the sign-in token when the app calls with one; required with X-API-Key.
    technician_id: Optional[str] = Field(default=None, min_length=1, max_length=100)
    customer: Customer
    location: Optional[Location] = None
    notes: Optional[str] = Field(default=None, max_length=2000)
    started_at: AwareDatetime
    readings: list[Reading] = Field(min_length=1, max_length=50)

    def to_payload(self) -> dict:
        """The JSON passed to submit_visit() in the database."""
        data = self.model_dump(mode="json", exclude={"readings"})
        data["readings"] = [r.to_row() for r in self.readings]
        return data


class SubmitOut(BaseModel):
    id: UUID
    created: bool  # false when this visit id was already saved
