"""Request and response shapes for the visit API (PRD §5.1)."""

from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, model_validator


class Sensor(str, Enum):
    temperature = "temperature"
    tds = "tds"
    voltage = "voltage"
    pressure = "pressure"
    sound = "sound"  # measured by the phone's microphone, not the device


class Result(str, Enum):
    pass_ = "pass"
    warn = "warn"
    fail = "fail"


class Status(str, Enum):
    settled = "settled"
    unstable = "unstable"
    fault = "fault"


# Unit and accepted range per sensor. Ranges are the PRD ranges with some
# headroom, to catch garbage (e.g. -127 °C from a disconnected DS18B20), not
# to judge pass/fail.
SENSOR_SPEC = {
    Sensor.temperature: ("C", -55.0, 125.0),
    Sensor.tds: ("ppm", 0.0, 2000.0),
    Sensor.voltage: ("V", 0.0, 300.0),
    Sensor.pressure: ("MPa", 0.0, 1.6),
    Sensor.sound: ("dB", 0.0, 150.0),
}


class Reading(BaseModel):
    sensor: Sensor
    value: float
    unit: str
    result: Result
    status: Optional[Status] = None
    battery_v: Optional[float] = Field(default=None, ge=0, le=10)
    device_id: Optional[str] = Field(default=None, min_length=1, max_length=64)
    firmware_version: Optional[str] = Field(default=None, min_length=1, max_length=32)
    taken_at: AwareDatetime

    @model_validator(mode="after")
    def check_sensor(self) -> "Reading":
        unit, low, high = SENSOR_SPEC[self.sensor]
        if self.unit != unit:
            raise ValueError(f"{self.sensor.value} must be in {unit}, got {self.unit!r}")
        if not low <= self.value <= high:
            raise ValueError(f"{self.sensor.value} {self.value} {unit} is outside {low}..{high}")
        if self.sensor != Sensor.sound and (self.device_id is None or self.firmware_version is None):
            raise ValueError("device readings need device_id and firmware_version")
        return self


class Customer(BaseModel):
    name: str = Field(min_length=1, max_length=200)
    phone: Optional[str] = Field(default=None, max_length=32)
    address: Optional[str] = Field(default=None, max_length=500)


class Location(BaseModel):
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)
    label: Optional[str] = Field(default=None, max_length=200)


class VisitIn(BaseModel):
    id: UUID  # generated by the app, so a retried submit is not saved twice
    technician_id: str = Field(min_length=1, max_length=100)
    customer: Customer
    location: Optional[Location] = None
    notes: Optional[str] = Field(default=None, max_length=2000)
    started_at: AwareDatetime
    readings: list[Reading] = Field(min_length=1, max_length=50)


class SubmitOut(BaseModel):
    id: UUID
    created: bool  # false when this visit id was already saved
