/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      // Material 3 colour roles: bg-primary, text-on-primary, bg-surface-container-high, ...
      colors: {
        "primary": "color-mix(in srgb, var(--md-primary) calc(<alpha-value> * 100%), transparent)",
        "on-primary": "color-mix(in srgb, var(--md-on-primary) calc(<alpha-value> * 100%), transparent)",
        "primary-container": "color-mix(in srgb, var(--md-primary-container) calc(<alpha-value> * 100%), transparent)",
        "on-primary-container": "color-mix(in srgb, var(--md-on-primary-container) calc(<alpha-value> * 100%), transparent)",
        "secondary": "color-mix(in srgb, var(--md-secondary) calc(<alpha-value> * 100%), transparent)",
        "on-secondary": "color-mix(in srgb, var(--md-on-secondary) calc(<alpha-value> * 100%), transparent)",
        "secondary-container": "color-mix(in srgb, var(--md-secondary-container) calc(<alpha-value> * 100%), transparent)",
        "on-secondary-container": "color-mix(in srgb, var(--md-on-secondary-container) calc(<alpha-value> * 100%), transparent)",
        "tertiary": "color-mix(in srgb, var(--md-tertiary) calc(<alpha-value> * 100%), transparent)",
        "on-tertiary": "color-mix(in srgb, var(--md-on-tertiary) calc(<alpha-value> * 100%), transparent)",
        "tertiary-container": "color-mix(in srgb, var(--md-tertiary-container) calc(<alpha-value> * 100%), transparent)",
        "on-tertiary-container": "color-mix(in srgb, var(--md-on-tertiary-container) calc(<alpha-value> * 100%), transparent)",
        "error": "color-mix(in srgb, var(--md-error) calc(<alpha-value> * 100%), transparent)",
        "on-error": "color-mix(in srgb, var(--md-on-error) calc(<alpha-value> * 100%), transparent)",
        "error-container": "color-mix(in srgb, var(--md-error-container) calc(<alpha-value> * 100%), transparent)",
        "on-error-container": "color-mix(in srgb, var(--md-on-error-container) calc(<alpha-value> * 100%), transparent)",
        "surface": "color-mix(in srgb, var(--md-surface) calc(<alpha-value> * 100%), transparent)",
        "on-surface": "color-mix(in srgb, var(--md-on-surface) calc(<alpha-value> * 100%), transparent)",
        "surface-variant": "color-mix(in srgb, var(--md-surface-variant) calc(<alpha-value> * 100%), transparent)",
        "on-surface-variant": "color-mix(in srgb, var(--md-on-surface-variant) calc(<alpha-value> * 100%), transparent)",
        "surface-container-lowest": "color-mix(in srgb, var(--md-surface-container-lowest) calc(<alpha-value> * 100%), transparent)",
        "surface-container-low": "color-mix(in srgb, var(--md-surface-container-low) calc(<alpha-value> * 100%), transparent)",
        "surface-container": "color-mix(in srgb, var(--md-surface-container) calc(<alpha-value> * 100%), transparent)",
        "surface-container-high": "color-mix(in srgb, var(--md-surface-container-high) calc(<alpha-value> * 100%), transparent)",
        "surface-container-highest": "color-mix(in srgb, var(--md-surface-container-highest) calc(<alpha-value> * 100%), transparent)",
        "outline": "color-mix(in srgb, var(--md-outline) calc(<alpha-value> * 100%), transparent)",
        "outline-variant": "color-mix(in srgb, var(--md-outline-variant) calc(<alpha-value> * 100%), transparent)",
        "inverse-surface": "color-mix(in srgb, var(--md-inverse-surface) calc(<alpha-value> * 100%), transparent)",
        "inverse-on-surface": "color-mix(in srgb, var(--md-inverse-on-surface) calc(<alpha-value> * 100%), transparent)",
        "inverse-primary": "color-mix(in srgb, var(--md-inverse-primary) calc(<alpha-value> * 100%), transparent)",
        "scrim": "color-mix(in srgb, var(--md-scrim) calc(<alpha-value> * 100%), transparent)",
        "ok": "color-mix(in srgb, var(--md-ok) calc(<alpha-value> * 100%), transparent)",
        "on-ok": "color-mix(in srgb, var(--md-on-ok) calc(<alpha-value> * 100%), transparent)",
        "ok-container": "color-mix(in srgb, var(--md-ok-container) calc(<alpha-value> * 100%), transparent)",
        "on-ok-container": "color-mix(in srgb, var(--md-on-ok-container) calc(<alpha-value> * 100%), transparent)",
        "warn": "color-mix(in srgb, var(--md-warn) calc(<alpha-value> * 100%), transparent)",
        "on-warn": "color-mix(in srgb, var(--md-on-warn) calc(<alpha-value> * 100%), transparent)",
        "warn-container": "color-mix(in srgb, var(--md-warn-container) calc(<alpha-value> * 100%), transparent)",
        "on-warn-container": "color-mix(in srgb, var(--md-on-warn-container) calc(<alpha-value> * 100%), transparent)",
        "fail": "color-mix(in srgb, var(--md-fail) calc(<alpha-value> * 100%), transparent)",
        "on-fail": "color-mix(in srgb, var(--md-on-fail) calc(<alpha-value> * 100%), transparent)",
        "fail-container": "color-mix(in srgb, var(--md-fail-container) calc(<alpha-value> * 100%), transparent)",
        "on-fail-container": "color-mix(in srgb, var(--md-on-fail-container) calc(<alpha-value> * 100%), transparent)",
      },
      borderRadius: {
        // M3 shape scale
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "28px",
      },
      boxShadow: {
        e1: "0 1px 2px rgba(0,0,0,.3), 0 1px 3px 1px rgba(0,0,0,.15)",
        e2: "0 1px 2px rgba(0,0,0,.3), 0 2px 6px 2px rgba(0,0,0,.15)",
        e3: "0 4px 8px 3px rgba(0,0,0,.15), 0 1px 3px rgba(0,0,0,.3)",
      },
    },
  },
  plugins: [],
};
