-- Visits and readings for the Hommiez field diagnostic tool.
-- Only the FastAPI backend (service_role key) reads and writes these tables:
-- RLS is on with no policies, so the public anon key gets nothing.

create table public.visits (
  id               uuid primary key,              -- generated by the app, so retries are safe
  technician_id    text not null check (length(technician_id) between 1 and 100),
  customer_name    text not null check (length(customer_name) between 1 and 200),
  customer_phone   text,
  customer_address text,
  latitude         double precision check (latitude between -90 and 90),
  longitude        double precision check (longitude between -180 and 180),
  location_label   text,
  notes            text,
  started_at       timestamptz not null,
  submitted_at     timestamptz not null default now()
);

create table public.readings (
  id               bigint generated always as identity primary key,
  visit_id         uuid not null references public.visits (id) on delete cascade,
  sensor           text not null check (sensor in ('temperature', 'tds', 'voltage', 'pressure', 'sound')),
  value            double precision not null,
  unit             text not null,
  result           text not null check (result in ('pass', 'warn', 'fail')),
  status           text check (status in ('settled', 'unstable', 'fault')),
  battery_v        real,
  device_id        text,
  firmware_version text,
  taken_at         timestamptz not null,
  created_at       timestamptz not null default now()
);

create index readings_visit_id_idx on public.readings (visit_id);
create index visits_technician_started_idx on public.visits (technician_id, started_at desc);

alter table public.visits enable row level security;
alter table public.readings enable row level security;

-- Saves a visit and all its readings in one transaction.
-- Calling it again with the same visit id changes nothing and returns created = false,
-- so the phone can safely retry after a dropped connection.
create function public.submit_visit(p jsonb)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  v_id uuid := (p ->> 'id')::uuid;
begin
  insert into visits (id, technician_id, customer_name, customer_phone, customer_address,
                      latitude, longitude, location_label, notes, started_at)
  values (
    v_id,
    p ->> 'technician_id',
    p -> 'customer' ->> 'name',
    p -> 'customer' ->> 'phone',
    p -> 'customer' ->> 'address',
    (p -> 'location' ->> 'latitude')::double precision,
    (p -> 'location' ->> 'longitude')::double precision,
    p -> 'location' ->> 'label',
    p ->> 'notes',
    (p ->> 'started_at')::timestamptz
  )
  on conflict (id) do nothing;

  if not found then
    return jsonb_build_object('id', v_id, 'created', false);
  end if;

  insert into readings (visit_id, sensor, value, unit, result, status, battery_v,
                        device_id, firmware_version, taken_at)
  select v_id, r.sensor, r.value, r.unit, r.result, r.status, r.battery_v,
         r.device_id, r.firmware_version, r.taken_at
  from jsonb_to_recordset(p -> 'readings') as r (
    sensor text, value double precision, unit text, result text, status text,
    battery_v real, device_id text, firmware_version text, taken_at timestamptz
  );

  return jsonb_build_object('id', v_id, 'created', true);
end;
$$;

revoke execute on function public.submit_visit(jsonb) from public, anon, authenticated;
grant execute on function public.submit_visit(jsonb) to service_role;
